### ISSUE TITLE
Adding German phrasal verbs 

### ISSUE THREAD

**Issue by d-ivashchuk** [d-ivashchuk/irregio-react#13]
This task is quite simple and requires only manual(or automated) filling of the list of phrasal verbs and their meanings.
### How to contribute

1. Fork this repo

2. Clone the repo to your local machine

3. Switch to branch phrasal-verbs-functionality 

4. Create new file`./src/container/data/phrasalVerbsDe.ts` and fill the list following the strucutre 
```[{pVerb:`abhängen`, prae:`von`, kasus:`D`},{...},...]```

Feel free to ask me questions if you need support or guidance. Thanks for helping out!

#### This issue is a part of #10 
 You are also welcome to look at the following issues:

- #12 Adding English phrasal verbs

- #9 Adding new languages

**Comment by amberjohnsonsmile** [comment]
Hi! I'd be happy to help with this.

**Comment by amberjohnsonsmile** [comment]
Here is the PR!
https://github.com/d-ivashchuk/irregio-react/pull/16

**Comment by d-ivashchuk** [comment]
Amazing, thanks for your input @amberjohnsonsmile !
