### ISSUE TITLE
Adding English translations to German phrasal verbs

### ISSUE THREAD

**Issue by d-ivashchuk** [d-ivashchuk/irregio-react#18]
## How to contribute
We already have German phrasal verbs but translation is lacking. If you fell like you can handle it, go ahead please!

1.  Fork this repo

2. Clone the repo to your local machine

3. Switch to branch phrasal-verbs-functionality

4. Go to `./src/container/data/phrasalVerbsDe.ts` and fill the list with translations

Feel free to ask me questions if you need support or guidance. Thanks for helping out!
This issue is a part of #10

You can also look at the following issues:

   #12  Adding German phrasal verbs

**Comment by spicyyboi** [comment]
How should the translations in `./src/container/data/phrasalVerbsDe.ts` be added? I figured a dictionary-key `meaning: ` as in `./src/containers/data/phrasalVerbs.ts` would make the most sense but i wanted to ask first to be sure.

**Comment by d-ivashchuk** [comment]
I think the best way to do that is to use key `translationGe`

**Comment by spicyyboi** [comment]
Alright, I'm on it. Do you want to have the translation formatted in a special way? For instance: 
`...
    {
      pVerb: "achten",
      prae: "auf",
      kasus: "A"
    },
...`
could have the translation `to look after (sth.)`, so I'm asking if you want the `to` or the `sth.` included or not.

**Comment by d-ivashchuk** [comment]
@spicyyboi Yeah, your suggestion is fine, let's do it that way `translationGe: 'to look after (sth.)'` and stick to this pattern!
