### ISSUE TITLE
Filling phrasal verbs list for English language

### ISSUE THREAD

**Issue by d-ivashchuk** [d-ivashchuk/irregio-react#21]
[Here is the link](https://www.englishclub.com/vocabulary/phrasal-verbs-list.htm) to the resource with quite comprehensive list of phrasal verbs. It would be really nice if we could have them in full amount to allow more people to get an accessible way of learning and practicing them!

### How to contribute

1. Fork this repo

2. Clone the repo to your local machine

3. Switch to branch phrasal-verbs-functionality 

4. Go to `./src/container/data/phrasalVerbs.ts` and continue filing the list 

Feel free to ask me questions if you need support or guidance. Thanks for helping out!

**Comment by Ashrey** [comment]
Pull done

**Comment by d-ivashchuk** [comment]
Great job! Seems like exactly what has been needed! Thanks, I will review and merge it in the next days!
